apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jokeservice
    managed-by: gopherguard
  name: jokeservice
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jokeservice
  template:
    metadata:
      labels:
        app: jokeservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: ERROR_RATE
          value: "0.20"
        - name: PANIC_RATE
          value: "0"
        - name: OOM_RATE
          value: "0.02"
        image: ghcr.io/tonyjoanes/jokeservice:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        name: jokeservice
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
