apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gopher-guard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gopher-guard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gopher-guard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gopher-guard.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gopher-guard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          image: {{ include "gopher-guard.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - /manager
          args:
            - --health-probe-bind-address=:{{ .Values.healthProbePort }}
            {{- if .Values.leaderElection }}
            - --leader-elect
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            {{- if .Values.metrics.secure }}
            - --metrics-secure
            {{- else }}
            - --metrics-secure=false
            {{- end }}
            {{- end }}
            {{- if .Values.prometheusURL }}
            - --prometheus-url={{ .Values.prometheusURL }}
            {{- end }}
          ports:
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
            - name: health
              containerPort: {{ .Values.healthProbePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.healthProbePort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.healthProbePort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
